{
 "title": "Cable Modem",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(netgear_cm_state_connected)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(netgear_cm_state_uptime_secs)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "expr": "max(netgear_cm_state_booted) by (file) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downstream Power",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "avg(netgear_cm_downstream_channel_power_dbmv{channel_id!=\"0\"}) by (frequency)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstream Power",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "avg(netgear_cm_upstream_channel_power_dbmv{channel_id!=\"0\"}) by (frequency)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downstream SNR",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "avg(netgear_cm_downstream_channel_snr_db{channel_id!=\"0\"}) by (frequency)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downstream Codewords",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "sum(rate(netgear_cm_downstream_channel_codewords_normal_total[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(netgear_cm_downstream_channel_codewords_correctable_total[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(netgear_cm_downstream_channel_codewords_uncorrectable_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downstream Uncorrectable Rate",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "avg(\n    rate(netgear_cm_downstream_channel_codewords_uncorrectable_total{channel_id!=\"0\"}[1m]) \n    / \n    (\n        rate(netgear_cm_downstream_channel_codewords_uncorrectable_total{channel_id!=\"0\"}[1m]) \n        + rate(netgear_cm_downstream_channel_codewords_correctable_total{channel_id!=\"0\"}[1m]) \n        + rate(netgear_cm_downstream_channel_codewords_normal_total{channel_id!=\"0\"}[1m])\n    )\n) by (frequency)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}